"""add agent_executions table

Revision ID: 5f66855cbbb7
Revises: 3a9499aeb5d7
Create Date: 2026-07-30 19:52:23.258433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f66855cbbb7'
down_revision: Union[str, None] = '3a9499aeb5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('input_content', sa.Text(), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
